# Generated by Django 5.2.17 on 2026-08-13 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.projeto')),
            ],
            options={
                'unique_together': {('nome', 'projeto')},
            },
        ),
        migrations.CreateModel(
            name='CasoDeTeste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('pre_condicao', models.TextField()),
                ('passos_reproducao', models.TextField()),
                ('resultado_esperado', models.TextField()),
                ('prioridade', models.CharField(choices=[('A', 'Alta'), ('M', 'Média'), ('B', 'Baixa')], default='M', max_length=1)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('O', 'Obsoleto'), ('R', 'Rascunho')], default='A', max_length=1)),
                ('observacao', models.TextField(blank=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.projeto')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casos_teste.modulo')),
            ],
        ),
    ]
