# Generated by Django 5.2.17 on 2026-09-17 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos_teste', '0002_casodeteste_atualizado_em_casodeteste_criado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='casodeteste',
            name='teste_atualizado_em',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 17, 19, 25, 7, 919721, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
