# Generated by Django 5.2.17 on 2026-09-22 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_documento_atualizado_em_documento_criado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriadocumento',
            name='obrigatoria',
            field=models.BooleanField(default=False),
        ),
    ]
