# Generated by Django 5.2.17 on 2026-08-13 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casos_teste', '0001_initial'),
        ('planos_teste', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Execucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsavel', models.CharField(max_length=50)),
                ('ambiente', models.CharField(choices=[('H', 'Homologação'), ('P', 'Produção')], default='H', max_length=1)),
                ('data_execucao', models.DateTimeField()),
                ('plano_de_teste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planos_teste.planodeteste')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoExecucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_execucao', models.CharField(choices=[('P', 'Passou'), ('F', 'Falhou'), ('B', 'Bloqueado'), ('N', 'Não Executado')], default='N', max_length=1)),
                ('executor', models.CharField(blank=True, max_length=50)),
                ('observacao', models.TextField(blank=True)),
                ('caso_de_teste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casos_teste.casodeteste')),
                ('execucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='execucoes.execucao')),
            ],
            options={
                'unique_together': {('execucao', 'caso_de_teste')},
            },
        ),
    ]
