# Generated by Django 5.2.17 on 2026-09-17 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execucoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='execucao',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='execucao',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 9, 17, 18, 32, 40, 851262, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultadoexecucao',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='resultadoexecucao',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 9, 17, 18, 32, 40, 851364, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
