# Generated by Django 5.2.17 on 2026-08-13 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casos_teste', '0001_initial'),
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoDeTeste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('revisor', models.CharField(blank=True, max_length=50)),
                ('casos_de_teste', models.ManyToManyField(to='casos_teste.casodeteste')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.projeto')),
            ],
            options={
                'unique_together': {('nome', 'projeto')},
            },
        ),
    ]
